version: "3.8"

services:
  services:
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
      environment:
        - discovery.type=single-node
      ports:
        - "9200:9200"
        - "9300:9300"
      volumes:
        - esdata:/usr/share/elasticsearch/data


  redis:
    image: redis:7.0
    #container_name: redis_container
    #restart: unless-stopped
    #command: ["redis-server", "--maxmemory", "20mb", "--maxmemory-policy", "allkeys-lru"]
    command: ["redis-server", "--maxmemory", "20mb", "--maxmemory-policy", "volatile-random"]
    ports:
      - "6379:6379"
      
  scraper:
    build: .
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb+srv://diego:diego@waze.5jx8mup.mongodb.net/?retryWrites=true&w=majority&appName=Waze"
    command: ["python", "scraper.py"]
    volumes:
      - .:/app
    working_dir: /app

  trafficgen:
    build: .
    depends_on:
      - mongodb
      - redis
    environment:
      MONGO_URI: "mongodb+srv://diego:diego@waze.5jx8mup.mongodb.net/?retryWrites=true&w=majority&appName=Waze"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TRAFFIC_EVENTS: 5000
      TRAFFIC_SAMPLE_SIZE: 20
      TRAFFIC_BASE_TTL: 60
      TRAFFIC_RATE: 2.0
      TRAFFIC_QUERIES: 100
    command: ["python", "traffic_generator.py"]

volumes:
  esdata:

